# -*- coding: utf-8 -*-
"""Sales Forecasting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pRjONVVwz-Hem-P_YGv4uHvIYF2Vu9VD
"""

!pip install faker

import pandas as pd
import random
from faker import Faker
import numpy as np

fake = Faker()

num_records = 500
data = []

for _ in range(num_records):
    date = fake.date_between(start_date='-2y', end_date='today')
    store = random.randint(1, 10)
    item = random.randint(100, 200)
    sales = random.randint(1, 50)
    region = random.choice(['North', 'South', 'East', 'West'])

    data.append([date, store, item, sales, region])

df = pd.DataFrame(data, columns=['Date', 'Store', 'Item', 'Sales', 'Region'])
df.head()

df['Date'] = pd.to_datetime(df['Date'])
df.isnull().sum()
df.drop_duplicates(inplace=True)
df = df.sort_values('Date')
df.head()

print("Total Sales:", df['Sales'].sum())
print("Average Sales:", df['Sales'].mean())
store_sales = df.groupby('Store')['Sales'].sum()
store_sales

import matplotlib.pyplot as plt
store_sales.plot(kind='bar')
plt.title("Sales by Store")
plt.xlabel("Store")
plt.ylabel("Sales")
plt.show()

